/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace CoffeeTrace {
      
    export type BatchStruct = {batchId: string, farmer: string, cooperative: string, origin: string, collectionDate: string, weight: string, station: string, washMethod: string, moisture: string, grade: string, cuppingScore: string, buyer: string, destination: string, shipDate: string, container: string, ipfsHash: string, isRegistered: boolean, lastUpdated: BigNumberish}

    export type BatchStructOutput = [batchId: string, farmer: string, cooperative: string, origin: string, collectionDate: string, weight: string, station: string, washMethod: string, moisture: string, grade: string, cuppingScore: string, buyer: string, destination: string, shipDate: string, container: string, ipfsHash: string, isRegistered: boolean, lastUpdated: bigint] & {batchId: string, farmer: string, cooperative: string, origin: string, collectionDate: string, weight: string, station: string, washMethod: string, moisture: string, grade: string, cuppingScore: string, buyer: string, destination: string, shipDate: string, container: string, ipfsHash: string, isRegistered: boolean, lastUpdated: bigint }
  
    }

  export interface CoffeeTraceInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "EXPORT_ROLE" | "INTAKE_ROLE" | "PROCESSING_ROLE" | "attachDocument" | "batchIds" | "batches" | "getBatch" | "getBatchCount" | "getRoleAdmin" | "getUserRoles" | "grantRole" | "hasRole" | "logExport" | "logProcessing" | "registerBatch" | "renounceRole" | "revokeRole" | "supportsInterface"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BatchRegistered" | "DocumentAttached" | "ExportLogged" | "ProcessingLogged" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'EXPORT_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'INTAKE_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PROCESSING_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'attachDocument', values: [string, string]): string;
encodeFunctionData(functionFragment: 'batchIds', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'batches', values: [string]): string;
encodeFunctionData(functionFragment: 'getBatch', values: [string]): string;
encodeFunctionData(functionFragment: 'getBatchCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getUserRoles', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'logExport', values: [string, string, string, string, string]): string;
encodeFunctionData(functionFragment: 'logProcessing', values: [string, string, string, string, string, string]): string;
encodeFunctionData(functionFragment: 'registerBatch', values: [string, string, string, string, string]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'EXPORT_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'INTAKE_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PROCESSING_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'attachDocument', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'batchIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'batches', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBatchCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserRoles', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'logExport', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'logProcessing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
  }

  
    export namespace BatchRegisteredEvent {
      export type InputTuple = [batchId: string, farmer: string, origin: string, timestamp: BigNumberish];
      export type OutputTuple = [batchId: string, farmer: string, origin: string, timestamp: bigint];
      export interface OutputObject {batchId: string, farmer: string, origin: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DocumentAttachedEvent {
      export type InputTuple = [batchId: string, ipfsHash: string, timestamp: BigNumberish];
      export type OutputTuple = [batchId: string, ipfsHash: string, timestamp: bigint];
      export interface OutputObject {batchId: string, ipfsHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExportLoggedEvent {
      export type InputTuple = [batchId: string, buyer: string, destination: string, timestamp: BigNumberish];
      export type OutputTuple = [batchId: string, buyer: string, destination: string, timestamp: bigint];
      export interface OutputObject {batchId: string, buyer: string, destination: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProcessingLoggedEvent {
      export type InputTuple = [batchId: string, station: string, grade: string, timestamp: BigNumberish];
      export type OutputTuple = [batchId: string, station: string, grade: string, timestamp: bigint];
      export interface OutputObject {batchId: string, station: string, grade: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CoffeeTrace extends BaseContract {
    
    connect(runner?: ContractRunner | null): CoffeeTrace;
    waitForDeployment(): Promise<this>;

    interface: CoffeeTraceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    EXPORT_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    INTAKE_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PROCESSING_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    attachDocument: TypedContractMethod<
      [_batchId: string, _ipfsHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    batchIds: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    batches: TypedContractMethod<
      [arg0: string, ],
      [[string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, boolean, bigint] & {batchId: string, farmer: string, cooperative: string, origin: string, collectionDate: string, weight: string, station: string, washMethod: string, moisture: string, grade: string, cuppingScore: string, buyer: string, destination: string, shipDate: string, container: string, ipfsHash: string, isRegistered: boolean, lastUpdated: bigint }],
      'view'
    >
    

    
    getBatch: TypedContractMethod<
      [_batchId: string, ],
      [CoffeeTrace.BatchStructOutput],
      'view'
    >
    

    
    getBatchCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getUserRoles: TypedContractMethod<
      [user: AddressLike, ],
      [[boolean, boolean, boolean, boolean]],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    logExport: TypedContractMethod<
      [_batchId: string, _buyer: string, _destination: string, _shipDate: string, _container: string, ],
      [void],
      'nonpayable'
    >
    

    
    logProcessing: TypedContractMethod<
      [_batchId: string, _station: string, _washMethod: string, _moisture: string, _grade: string, _cuppingScore: string, ],
      [void],
      'nonpayable'
    >
    

    
    registerBatch: TypedContractMethod<
      [_farmer: string, _cooperative: string, _origin: string, _collectionDate: string, _weight: string, ],
      [string],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'EXPORT_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'INTAKE_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PROCESSING_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'attachDocument'): TypedContractMethod<
      [_batchId: string, _ipfsHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'batchIds'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'batches'): TypedContractMethod<
      [arg0: string, ],
      [[string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, boolean, bigint] & {batchId: string, farmer: string, cooperative: string, origin: string, collectionDate: string, weight: string, station: string, washMethod: string, moisture: string, grade: string, cuppingScore: string, buyer: string, destination: string, shipDate: string, container: string, ipfsHash: string, isRegistered: boolean, lastUpdated: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getBatch'): TypedContractMethod<
      [_batchId: string, ],
      [CoffeeTrace.BatchStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getBatchCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getUserRoles'): TypedContractMethod<
      [user: AddressLike, ],
      [[boolean, boolean, boolean, boolean]],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'logExport'): TypedContractMethod<
      [_batchId: string, _buyer: string, _destination: string, _shipDate: string, _container: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'logProcessing'): TypedContractMethod<
      [_batchId: string, _station: string, _washMethod: string, _moisture: string, _grade: string, _cuppingScore: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerBatch'): TypedContractMethod<
      [_farmer: string, _cooperative: string, _origin: string, _collectionDate: string, _weight: string, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'BatchRegistered'): TypedContractEvent<BatchRegisteredEvent.InputTuple, BatchRegisteredEvent.OutputTuple, BatchRegisteredEvent.OutputObject>;
getEvent(key: 'DocumentAttached'): TypedContractEvent<DocumentAttachedEvent.InputTuple, DocumentAttachedEvent.OutputTuple, DocumentAttachedEvent.OutputObject>;
getEvent(key: 'ExportLogged'): TypedContractEvent<ExportLoggedEvent.InputTuple, ExportLoggedEvent.OutputTuple, ExportLoggedEvent.OutputObject>;
getEvent(key: 'ProcessingLogged'): TypedContractEvent<ProcessingLoggedEvent.InputTuple, ProcessingLoggedEvent.OutputTuple, ProcessingLoggedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;

    filters: {
      
      'BatchRegistered(string,string,string,uint256)': TypedContractEvent<BatchRegisteredEvent.InputTuple, BatchRegisteredEvent.OutputTuple, BatchRegisteredEvent.OutputObject>;
      BatchRegistered: TypedContractEvent<BatchRegisteredEvent.InputTuple, BatchRegisteredEvent.OutputTuple, BatchRegisteredEvent.OutputObject>;
    

      'DocumentAttached(string,string,uint256)': TypedContractEvent<DocumentAttachedEvent.InputTuple, DocumentAttachedEvent.OutputTuple, DocumentAttachedEvent.OutputObject>;
      DocumentAttached: TypedContractEvent<DocumentAttachedEvent.InputTuple, DocumentAttachedEvent.OutputTuple, DocumentAttachedEvent.OutputObject>;
    

      'ExportLogged(string,string,string,uint256)': TypedContractEvent<ExportLoggedEvent.InputTuple, ExportLoggedEvent.OutputTuple, ExportLoggedEvent.OutputObject>;
      ExportLogged: TypedContractEvent<ExportLoggedEvent.InputTuple, ExportLoggedEvent.OutputTuple, ExportLoggedEvent.OutputObject>;
    

      'ProcessingLogged(string,string,string,uint256)': TypedContractEvent<ProcessingLoggedEvent.InputTuple, ProcessingLoggedEvent.OutputTuple, ProcessingLoggedEvent.OutputObject>;
      ProcessingLogged: TypedContractEvent<ProcessingLoggedEvent.InputTuple, ProcessingLoggedEvent.OutputTuple, ProcessingLoggedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    
    };
  }